/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,ts,md}'],
  theme: {
    extend: {
      colors: {
        primary: 'var(--gr-primary)',
        'primary-hover': 'var(--gr-primary-hover)',
        'primary-pressed': 'var(--gr-primary-pressed)',
        'primary-subtle': 'var(--gr-primary-subtle)',
        'on-primary': 'var(--gr-on-primary)',
        cream: 'var(--gr-cream)',
        bg: 'var(--gr-bg)',
        'bg-raised': 'var(--gr-bg-raised)',
        surface: 'var(--gr-surface)',
        'surface-muted': 'var(--gr-surface-muted)',
        'surface-sunken': 'var(--gr-surface-sunken)',
        'text-primary': 'var(--gr-text-primary)',
        'text-secondary': 'var(--gr-text-secondary)',
        'text-tertiary': 'var(--gr-text-tertiary)',
        'text-on-brand': 'var(--gr-text-on-brand)',
        'border-subtle': 'var(--gr-border-subtle)',
        'border-default': 'var(--gr-border-default)',
        success: 'var(--gr-success)',
        warning: 'var(--gr-warning)',
        danger: 'var(--gr-danger)',
        info: 'var(--gr-info)',
      },
      fontFamily: {
        display: 'var(--gr-font-display)',
        body: 'var(--gr-font-body)',
        mono: 'var(--gr-font-mono)',
      },
      fontSize: {
        xs: 'var(--gr-text-xs)',
        sm: 'var(--gr-text-sm)',
        base: 'var(--gr-text-base)',
        lg: 'var(--gr-text-lg)',
        xl: 'var(--gr-text-xl)',
        '2xl': 'var(--gr-text-2xl)',
        '3xl': 'var(--gr-text-3xl)',
        '4xl': 'var(--gr-text-4xl)',
        '5xl': 'var(--gr-text-5xl)',
      },
      fontWeight: {
        light: '300',
        normal: '400',
        medium: '500',
        bold: '700',
        extrabold: '800',
        black: '900',
      },
      letterSpacing: {
        tightest: '-0.02em',
        wide: '0.04em',
        widest: '0.15em',
      },
      borderRadius: {
        xs: 'var(--gr-radius-xs)',
        sm: 'var(--gr-radius-sm)',
        md: 'var(--gr-radius-md)',
        lg: 'var(--gr-radius-lg)',
        xl: 'var(--gr-radius-xl)',
        '2xl': 'var(--gr-radius-2xl)',
        pill: 'var(--gr-radius-pill)',
      },
      boxShadow: {
        xs: 'var(--gr-elev-xs)',
        sm: 'var(--gr-elev-sm)',
        md: 'var(--gr-elev-md)',
        lg: 'var(--gr-elev-lg)',
        xl: 'var(--gr-elev-xl)',
      },
      maxWidth: {
        container: 'var(--gr-container-xl)',
        content: 'var(--gr-content-max-width)',
      },
      transitionDuration: {
        instant: '80ms',
        fast: '140ms',
        base: '220ms',
        slow: '360ms',
      },
      transitionTimingFunction: {
        standard: 'var(--gr-ease-standard)',
        decelerate: 'var(--gr-ease-decelerate)',
        accelerate: 'var(--gr-ease-accelerate)',
        spring: 'var(--gr-ease-spring)',
      },
    },
  },
  plugins: [],
};
